name-template: "Draft"
tag-template: "draft"
categories:
  - title: "⬆️ Dependencies"
    collapse-after: 3
    labels:
      - "dependencies"

  - title: "🐛 Bug Fixes"
    labels:
      - "bugfix"

  - title: "🚀 Features"
    labels:
      - "feature"

  - title: "📄 Documentation"
    labels:
      - "documentation"

  - title: "🧰 Maintenance"
    labels:
      - "maintenance"
      - "chore"
      - "ci"

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'

template: |
  $CHANGES
