apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bitwarden-cli.fullname" . }}
  labels:
    {{- include "bitwarden-cli.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bitwarden-cli.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bitwarden-cli.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bitwarden-cli.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: BW_HOST
              value: {{ .Values.config.bwHost | quote }}
            - name: BW_PORT
              value: {{ .Values.container.port | quote }}
            - name: BITWARDENCLI_APPDATA_DIR
              value: {{ .Values.persistence.mountPath | quote }}
            - name: BITWARDENCLI_DEBUG
              value: {{ .Values.config.bitwardenCliDebug | quote }}
            - name: BW_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: {{ include "bitwarden-cli.authSecretName" . }}
                  key: BW_CLIENTID
            - name: BW_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "bitwarden-cli.authSecretName" . }}
                  key: BW_CLIENTSECRET
            - name: BW_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "bitwarden-cli.authSecretName" . }}
                  key: BW_PASSWORD
          ports:
            - name: http
              containerPort: {{ .Values.container.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: appdata
              mountPath: {{ .Values.persistence.mountPath | quote }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          {{- if not $.Values.persistence.enabled }}
          volumeMounts:
          {{- end }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: appdata
          persistentVolumeClaim:
            claimName: {{ include "bitwarden-cli.appdataPvcName" . }}
      {{- end }}
      {{- with .Values.volumes }}
      {{- if not $.Values.persistence.enabled }}
      volumes:
      {{- end }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
