{{- if not .Values.auth.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bitwarden-cli.authSecretName" . }}
  labels:
    {{- include "bitwarden-cli.labels" . | nindent 4 }}
type: Opaque
stringData:
  BW_CLIENTID: {{ required "auth.clientId is required when auth.existingSecret is empty" .Values.auth.clientId | quote }}
  BW_CLIENTSECRET: {{ required "auth.clientSecret is required when auth.existingSecret is empty" .Values.auth.clientSecret | quote }}
  BW_PASSWORD: {{ required "auth.password is required when auth.existingSecret is empty" .Values.auth.password | quote }}
{{- end }}
