name: Status

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v6

      - uses: pre-commit/action@v3.0.1

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build the Helm chart
        run: |
          helm template bitwarden-cli helm-charts/bitwarden-cli
